### PR TITLE
Merge it now

### PR DESCRIPTION
**Pull request by baalajimaestro**

### CODE REVIEW

**Comment by songotenks69** [comment]
@baalajimaestro Th0g

**Comment by MrYacha** [comment]
@songotenks69 ;-;

**Comment by MrYacha** [comment]
@MrYacha tf?

**Comment by songotenks69** [comment]
@MrYacha Email reply ghey

**Comment by MrYacha** [comment]
@songotenks69 ;-; It a sad GitHub bot

**Comment by Rishu751** [comment]
VoLTE is not working

**Comment by baalajimaestro** [comment]
@Rishu751 how does VoLTE relate to sophie bot on in any case this PR itself?
Please don't spam.

**Comment by songotenks69** [comment]
__bruh__

**Pull request merged**
